export const PricingPlans = [
  {
    id: 1,
    level: "join now",
    plan: "basic",
    features: [
      "Access to private Basic community channel",
      "Dedicated mentoring and support",
      "Unlimited access to marketing content material from the SocialFi team",
    ],
    pricing: "free",
    isMonthly: false,
    borderColor: "",
    stripeId: "",
  },
  {
    id: 2,
    level: "junior",
    plan: "silver",
    features: [
      "Intro Series of SocialFi Academy",
      "Access to the private Silver community channel",
      "Assigned mentor from the SocialFi team including direct message and weekly group calls",
      "Onboarding to Fluencr.xyz with your mentor",
      "Access to advanced marketing materials, education and content packages",
    ],
    pricing: "USD 49",
    isMonthly: true,
    borderColor: "",
    stripeId: "price_1N2hkHBALhlJEB15jcLxYOk2",
  },
  {
    id: 3,
    level: "best value",
    plan: "gold",
    features: [
      "Unlimited access to SocialFi Academy private Gold community channel",
      "Assigned mentor from the SocialFi team including bi-weekly calls and one-on-one mentoring.",
      "Onboarding to Fluencr.xyz Gold Membership offering 20% kickback on product sales + 10% kickback on referrals future sales",
      "Access to advanced marketing materials, education and content packages",
      "Loyalty airdrops and perfomance bonuses",
    ],
    pricing: "USD 249",
    isMonthly: true,
    borderColor: "#E8B923",
    stripeId: "price_1N2fKBBALhlJEB15vzKCcmsI",
  },
  {
    id: 4,
    level: "expert",
    plan: "diamond",
    features: [
      "Full commission from product sales and referral fees",
      "Full access to discord channels including Diamond Citadel",
      "24/7 one-on-one support on demand",
      "Exclusive pre-product access",
      "Custom feature development",
      "Get investment and operations support for your own business",
    ],
    pricing: "USD 1889",
    isMonthly: true,
    borderColor: "hotpink",
    stripeId: "price_1N2fJXBALhlJEB15cNFZvYXb",
  },
];
